# silence_plugin - 自动生成的配置文件
# 使麦麦在合适的时候保持沉默

# 插件基本配置
[plugin]

# 插件配置文件版本号
config_version = "0.1.0"

# 是否启用插件（总开关）
enabled = true


[components]

# 是否启用沉默动作组件
enable_silence_action = true

# 是否启用沉默命令组件
enable_silence_command = true

# 是否启用沉默事件处理器组件
enable_silence_event_handler = true


[permissions]

# 能够使用沉默命令的用户QQ号列表
admin_users = [629995608]


[adjustment]

# 是否禁用其他命令组件
disable_command = true

# 低级别沉默时间范围，单位为秒，格式为[min,max]
low_case = [120, 600]

# 中级别沉默时间范围，单位为秒，格式为[min,max]
medium_case = [600, 1200]

# 高级别沉默时间范围，单位为秒，格式为[min,max]
serious_case = [1200, 5400]


